name: godot-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install scons mingw-w64

      - name: test scons
        run: |
          ls
          scons perform=list
          

